f5/otel-arrow-adapter

pkg/benchmark/dataset/real_trace_dataset.go
pkg/benchmark/dataset/synthetic_dataset.go
pkg/datagen/data_generator.go
pkg/datagen/default.go
pkg/datagen/logs.go
pkg/datagen/metrics.go
pkg/datagen/trace.go
pkg/otel/arrow_record/producer_consumer_test.go
pkg/otel/logs/validation_test.go
pkg/otel/metrics/validation_test.go
pkg/otel/metrics_test/arrow_to_otlp_test.go
pkg/otel/metrics_test/otlp_to_arrow_test.go
pkg/otel/traces/validation_test.go
tools/logs_gen/main.go
tools/metrics_gen/main.go
tools/trace_gen/main.go

This changes the data generator to be deterministic , which makes the cases identified by the fuzzer reproducible.
Then, running `go test -fuzz .` in `pkg/otel/arrow_record` begins searching for problematic inputs. The test framework saves data to a local `testdata` directory, which helps it go faster on subsequent runs.
The first test case I discovered causes the process under test to OOM.
```
go test -v -run=FuzzProducerConsumerTraces/bd53d08feeddb625ad75ac78e4f9b018e408ef38f6a49ddf9715b12f7d2def16
```

Add a traces producer/consumer fuzz test

---

pkg/otel/arrow_record/consumer.go
pkg/otel/arrow_record/mock/mock.go
pkg/otel/arrow_record/producer.go
pkg/otel/arrow_record/producer_consumer_test.go

Issue: #53 
Each `ipc.Writer` must be closed after usage to avoid this type of memory leak.
A method `Producer.Close` has been added and the code/tests has been updated accordingly.
@jmacd in the collector you must call the `Close` method for each producer created.

Memory leak issue in otlp arrow producer

---

go.mod
go.sum

No code changes are needed; this version was released today. This will prevent us from adopting anything newly deprecated by mistake.

Update to OTelCol pdata v0.66.0

---

go.mod
go.sum
pkg/benchmark/dataset/real_trace_dataset.go

Updates to [sha 33cdc7907c2d1cfa447e822383baffc2b3c778f0 of the OTel collector, corresponding with release v0.67 containing pdata 1.0-rc1](https://github.com/open-telemetry/opentelemetry-collector/releases/tag/v0.67.0).
Only a minor change related to TraceID/SpanID, which have lost built-in hex-string methods.

Update to OTC pdata 1.0-rc1

---

README.md
tools/doc_schema_gen/main.go

This PR aims to generate a YAML representation of each Arrow schema used in this project in order to have a synchronized schema documentation in this project and in the corresponding OTEP.
GH issue: #79 
EDIT:  The SchemaDocGen CLI  generates the following YAML schema declaration based on the source code.
```yaml
attributes: &attributes                 # arrow map
key: string_dictionary | string       # string_dictionary by default, fallback to string when cardinality too high
value:                                # arrow sparse union
str: string_dictionary | string     # string_dictionary by default, fallback to string when cardinality too high
i64: int64
f64: float64
bool: bool
binary: binary_dictionary | binary  # binary_dictionary by default, fallback to binary when cardinality too …
```

Generate Arrow Schema documentation from code

---

api/collector/arrow/v1/arrow_service.pb.go
collector/gen/receiver/otlpreceiver/internal/arrow/arrow_test.go
proto/opentelemetry/proto/collector/arrow/v1/arrow_service.proto

Re-do of https://github.com/f5/otel-arrow-adapter/pull/84
Adds an optional field that allows transmission of http headers as bytes, to be encoded using hpack as would be done by a standard http2 (grpc) connection. We will use https://pkg.go.dev/golang.org/x/net/http2/hpack to implement this.

Make the optional headers field bytes, specified to use hpack

---

collector/examples/metadata-bridge/edge-collector.yaml
collector/examples/metadata-bridge/saas-collector.yaml
collector/examples/printer/printer.go
go.mod
go.sum

This also updates both bridge examples with comments and includes a printer to make diagnostics easy. (The logging exporter does not print headers, which the demo printer does.)

Add an example of a bridge that carries per-request metadata

---

collector/cmd/otelarrowcol/go.sum
collector/go.mod
collector/go.sum

The gRPC dependency was inadvertently set to v1.52.3 which appears to break things for us internally.

gRPC to v1.51.0

---

pkg/werror/error.go
pkg/werror/error_test.go

#127 
Function name is correct for 'WrapWithContext', but incorrect for 'Wrap', and 'WrapWithMsg'.

Fix error in werror.Wrap and werror.WrapWithMsg

---

pkg/otel/arrow_record/producer.go

In situations where we receive multiple OTel objects, there is a buffer that gets reused across different objects within the same batch. To prevent memory reuse issues, it's essential to create a copy of this buffer.

Fix memory reuse issue

---

go.mod
go.sum
pkg/benchmark/profileable/arrow/logs.go
pkg/benchmark/profileable/arrow/metrics.go
pkg/benchmark/profileable/arrow/traces.go
pkg/otel/arrow_record/producer.go
pkg/otel/common/arrow/any_value.go
pkg/otel/common/arrow/attributes.go
pkg/otel/logs/arrow/all_test.go
pkg/otel/logs/arrow/logs.go
pkg/otel/logs/arrow/optimizer.go
pkg/otel/logs/validation_test.go
pkg/otel/metrics/arrow/all_test.go
pkg/otel/metrics/arrow/metrics.go
pkg/otel/metrics/arrow/optimizer.go
pkg/otel/metrics/otlp/metrics_test.go
pkg/otel/metrics/validation_test.go
pkg/otel/traces/arrow/all_test.go
pkg/otel/traces/arrow/empty_trace_test.go
pkg/otel/traces/arrow/optimizer.go
pkg/otel/traces/arrow/traces.go
pkg/otel/traces/validation_test.go
tools/trace_benchmark/main.go

Example of statistics generated for traces.
Similar statistics exist for metrics and logs.
Options have been added to the `Producer` to enable the stats recording per OTel object. By default the stats recording is not enabled.
Memory consumption: ~2244 bytes/histogram

Collect a bunch of stats in the TracesOptimizer.

---

collector/gen/receiver/otlpreceiver/internal/arrow/arrow.go

This avoids crashing for data that can't be processed.

Return errors for unsupported signals

---

collector/gen/receiver/otlpreceiver/config.go
collector/gen/receiver/otlpreceiver/config_test.go
collector/gen/receiver/otlpreceiver/factory.go
collector/gen/receiver/otlpreceiver/factory_test.go
collector/gen/receiver/otlpreceiver/otlp.go
collector/gen/receiver/otlpreceiver/otlp_test.go
collector/gen/receiver/otlpreceiver/testdata/arrow_without_grpc.yaml
collector/gen/receiver/otlpreceiver/testdata/config.yaml

As a stand-alone component, the Arrow receiver should be enabled by default.

Arrow receiver: enabled by default

---

collector/gen/exporter/otlpexporter/config.go
collector/gen/exporter/otlpexporter/config_test.go
collector/gen/exporter/otlpexporter/factory.go
collector/gen/exporter/otlpexporter/factory_test.go
collector/gen/exporter/otlpexporter/otlp.go
collector/gen/exporter/otlpexporter/otlp_test.go
collector/gen/exporter/otlpexporter/testdata/config.yaml

As a stand-alone component, the Arrow exporter should be enabled by default and use NumCPU streams.

Arrow exporter: enabled by default w/ NumCPU streams

---

pkg/otel/logs/arrow/all_test.go
pkg/otel/traces/arrow/all_test.go
pkg/otel/traces/arrow/empty_trace_test.go

The same ProducerStats was used concurrently in multiple unit tests.

fix data race issue in traces/all_tests

---

collector/gen/receiver/otlpreceiver/otlp.go
collector/gen/receiver/otlpreceiver/otlp_test.go

Observed a crash when an Arrow receiver tried to accept data despite having Disabled: true in its config. 
This stems from the new per-signal services, which were not checking for disabled before registering. Extends a test to be sure we don't crash in this scenario.

Disable arrow receiver when Disabled=true on all services

---

collector/gen/internal/netstats/handler.go
collector/gen/internal/netstats/netstats.go
collector/gen/internal/netstats/netstats_test.go

Part of https://github.com/f5/otel-arrow-adapter/issues/119
Adds a `method` attribute to the counters in collector/gen/internal/netstats. This will help us know when downgrades are happening, for example.

Add the RPC method name to the netstats counters

---

pkg/otel/common/arrow/analyzer.go
pkg/otel/metrics/arrow/optimizer.go
pkg/otel/traces/arrow/analyzer.go
pkg/otel/traces/arrow/optimizer.go

Minor edit for consistency. The use of a pointer to `ptrace.Span` and `pmetric.Metric` raises flags about how these optimizers work, and it appears to be unnecessary. Note that these types are pointers under-the-hood anyway, and the optimizer was not using these as reference types.
Also note: the logs optimizer appears to work differently (slightly), so no change there. (Tangent: why does the logs optimizer use a `*ResScope` where the two others in-line the flattened thing?)

Remove pointers in two of the optimizers

---

pkg/datagen/default.go
pkg/otel/arrow_record/producer_consumer_test.go
pkg/otel/logs/otlp/logs.go
pkg/otel/metrics/otlp/metrics.go
pkg/otel/traces/otlp/traces.go

This corrects a problem discovered in an environment where Scope fields were unused, thus constant across Resources. In the fix here, which is also tested, the current scopeID value being used in the Producer would be incorrect since it matches the previous _from a different resource_.

Reset the scope ID when resource ID changes

---

collector/processor/obfuscationprocessor/processor.go
collector/processor/obfuscationprocessor/processor_test.go

Resolves https://github.com/f5/otel-arrow-adapter/issues/192
This PR resolves an issue where only string attribute values were being obfuscated. This was an issue because strings can be nested in other value type like a slice or map.
(cc @jmacd)

[issue-192] obfuscation of nested slices and maps
